spring:
  jpa:
    hibernate:
      ddl-auto: create # ??? ?? ?????.
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    base-package: com.ssu.commerce.book
    title: book api
    version: 1.0

logging:
  level:
    p6spy: info
