grpc:
  server:
    port: 9091

spring:
  jpa:
    hibernate:
      ddl-auto: create # test
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: user-service
    main:
      allow-circular-references: true

springdoc:
  swagger-ui:
    base-package: com.ssu.commerce.book
    title: book api
    version: 1.0

logging:
  level:
    p6spy: info

