name: Run Tests on Pull Request

on:
  pull_request:
    branches: ['*']

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v5

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache gradle modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          USERNAME: ${{secrets.USERNAME}}
          TOKEN: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew clean test jacocoTestReport sonarqube --stacktrace --profile

      - name: SonarQube Scan
        run: |
          sonar-scanner \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  \
          -Dsonar.login=${{ secrets.SONAR_LOGIN }} \
          -Dsonar.password=${{ secrets.SONAR_PASSWORD }} \
          -Dsonar.projectKey=book-server \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.language=java \
          -Dsonar.java.source=11 \
          -Dsonar.verbose=true \
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
          -Dsonar.scm.provider=git \
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
          -Dsonar.pullrequest.base=${{ github.base_ref }} \
          -Dsonar.pullrequest.github.repository=${{ github.repository }} \
          -Dsonar.sources=api/src \
          -Dsonar.java.binaries=api/build/classes \
          -Dsonar.log.level=INFO \

      - name: Test Coverage
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew jacocoTestCoverageVerification --stacktrace --profile

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 📝 테스트 커버리지 리포트입니다
          paths: |
            ${{ github.workspace }}/api/build/reports/**/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 57.65
          min-coverage-changed-files: 100

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
